name: Test manually trigger GitHub Actions

on:
  repository_dispatch:
    types: build-sw
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bazel
        run: |
          sudo apt install apt-transport-https curl gnupg -y
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update
          sudo apt-get install bazel
          sudo apt install default-jdk
      - name: Execute build
        run: |
          bazel build :hello-world --build_event_text_file=bazel_event.json
      - name: View bazel_event.json
        run: 'cat bazel_event.json'
